---

# Site settings

title: Your Name
description: Your personal website
url: https://yourusername.github.io
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github:
  username: yourusername
  repository: yourusername.github.io

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
