---
# # Variables
# owner_name: "{{site.github.owner_name}}"
# repository_name: "{{site.github.repository_name}}"

# Site settings
title: "${{ github.repository_owner }}'s Personal Website"
description: "A personal website for ${{ github.repository_owner }}"
url: "https://${{ github.repository_owner }}.github.io"
baseurl: "/${{ github.repository }}"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github:
  username: "${{ github.repository_owner }}"
  repository: "${{ github.repository }}"

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
