---


# Site settings

title: Your Name
description: Your personal website
url: https://yourusername.github.io
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
profile:
  username: "Ashhad"
  repository: yourusername.github.io

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

data:
  about-me: about-me.yaml
